name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag (vd: v1.0.0)"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout detours
        run: git clone --depth=1 https://github.com/microsoft/detours detours

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Configure
        run: xmake f -p windows -a x64 -m release

      - name: Build
        run: xmake

      - name: Package
        shell: pwsh
        run: |
          $tag = if ("${{ github.event_name }}" -eq "workflow_dispatch") { "${{ inputs.tag }}" } else { "${{ github.ref_name }}" }
          $out = "edge_portable-$tag"
          New-Item -ItemType Directory $out
          Copy-Item build\release\version.dll $out\
          Copy-Item chrome++.ini              $out\
          Get-ChildItem README.md -ErrorAction SilentlyContinue | Copy-Item -Destination $out\
          Compress-Archive -Path $out -DestinationPath "$out.zip"
          echo "TAG=$tag" >> $env:GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: edge_portable-${{ env.TAG }}.zip
          generate_release_notes: true
